CREATE TABLE task (
  id VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  introduction LONGTEXT NOT NULL,
  teamwork TINYINT(1) DEFAULT 1 NOT NULL,
  draft TINYINT(1) DEFAULT 1 NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
