CREATE TABLE task_assignee (
  id VARCHAR(50) NOT NULL,
  task_id VARCHAR(50) DEFAULT NULL,
  member_id VARCHAR(50) DEFAULT NULL,
  admin TINYINT(1) DEFAULT 1 NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  INDEX IDX_3C5D16408DB60186 (task_id),
  INDEX IDX_3C5D16407597D3FE (member_id),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE task_assignee ADD CONSTRAINT FK_3C5D16408DB60186 FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE task_assignee ADD CONSTRAINT FK_3C5D16407597D3FE FOREIGN KEY (member_id) REFERENCES member (id);
