CREATE TABLE task_report (
  id VARCHAR(50) NOT NULL,
  task_id VARCHAR(50) DEFAULT NULL,
  member_id VARCHAR(50) DEFAULT NULL,
  summary LONGTEXT NOT NULL,
  plan LONGTEXT NOT NULL,
  risk LONGTEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  INDEX IDX_FF86F3578DB60186 (task_id),
  INDEX IDX_FF86F3577597D3FE (member_id),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE task_report ADD CONSTRAINT FK_FF86F3578DB60186 FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE task_report ADD CONSTRAINT FK_FF86F3577597D3FE FOREIGN KEY (member_id) REFERENCES member (id);
